# Generated by Django 4.2.7 on 2023-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
