# Generated by Django 4.2.7 on 2023-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_extract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pdfs',
            name='pdf',
            field=models.FileField(upload_to='C:\\Users\\Vrdella\\Desktop\\images'),
        ),
    ]
